### ISSUE TITLE
api enumeration possible

### ISSUE THREAD

**Issue by benlarsendk** [dentych/dinner-dash-old#45]
By busting the /api/% on the API, one can get information wether or not there is a function based on the return value of either 404 or unauthorized. This should be the same response to ensure enumeration is not possible

**Comment by dentych** [comment]
ok

**Comment by dentych** [comment]
Sorry for my colleague dentych, he is a moron. We will look into this and fix it in the next release.

**Comment by dentych** [comment]
Actually we don't care
